#!/bin/sh
### BEGIN INIT INFO
# Provides:          poolTTY
# Required-Start:    $local_fs $network $named $time $syslog $all
# Required-Stop:     $local_fs $network $named $time $syslog $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Start/Stop socat, Pool Controller (serial port to ethernet!)
### END INIT INFO

SCRIPT="/usr/bin/daemon --respawn --name poolTTY --pidfiles /var/run --stdout daemon.info --stderr daemon.err -- /usr/bin/socat TCP-LISTEN:9801,reuseaddr FILE:/dev/ttyUSB0,b9600,raw"
RUNAS=root
PIDFILE=/var/run/poolTTY.pid

start() {
  if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
    echo 'poolTTY already running'
    return 1
  fi
  echo 'Starting poolTTY ...'
  su -c "$SCRIPT" $RUNAS
  echo 'poolTTY started'
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'poolTTY not running'
    return 1
  fi
  echo 'Stopping poolTTY ...'
  pkill -F "$PIDFILE" && rm -f "$PIDFILE"
  echo 'poolTTY stopped'
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
